// Single inclusion point for drivers. In the future this file will likely be
// automatically generated by CMake.

#ifndef _CAR_DRIVER_LIST_H_
#define _CAR_DRIVER_LIST_H_

///////////////////////////////////////////////////////////////////////////////
// Global map of driver name to driver creation function pointers:
///////////////////////////////////////////////////////////////////////////////
std::map<std::string,CarDriverInterface*(*)()> g_mDriverTable;

#include "RPG/Devices/Car/Drivers/SimulatedCarDriver/SimulatedCarDriver.h"
CarDriverRegisteryEntry<SimulatedCarDriver> _SimulatedCarDriver( "SimulatedCarDriver" );

#endif	// CAR_DRIVER_LIST_H

