// Single inclusion point for drivers. In the future this file will likely be
// automatically generated by CMake.

#ifndef _IMU_DRIVER_LIST_H_
#define _IMU_DRIVER_LIST_H_

///////////////////////////////////////////////////////////////////////////////
// Global map of driver name to driver creation function pointers:
std::map<std::string,IMUDriver*(*)()> g_mIMUDriverTable;

#ifdef USE_MICROSTRAIN
#include "RPG/IMU/Drivers/MicroStrain/MicroStrainDriver.h"
IMUDriverRegisteryEntry<MicroStrainDriver> _MicroStrainReg( "MicroStrain" );
#endif

#ifdef USE_IMULOG
#include "RPG/IMU/Drivers/IMULog/IMULogDriver.h"
IMUDriverRegisteryEntry<IMULogDriver> _IMULogReg( "IMULog" );
#endif

#ifdef USE_PHIDGETS
#include "RPG/IMU/Drivers/Phidgets/PhidgetsDriver.h"
IMUDriverRegisteryEntry<PhidgetsDriver> _PhidgetsReg( "Phidgets" );
#endif

#endif

