/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_gwu_rpg_androidnodecam_AndNodeCam */

#ifndef _Included_edu_gwu_rpg_androidnodecam_AndNodeCam
#define _Included_edu_gwu_rpg_androidnodecam_AndNodeCam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_gwu_rpg_androidnodecam_AndNodeCam
 * Method:    sendData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_edu_gwu_rpg_androidnodecam_AndNodeCam_sendData
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     edu_gwu_rpg_androidnodecam_AndNodeCam
 * Method:    Initialize
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_edu_gwu_rpg_androidnodecam_AndNodeCam_Initialize
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
