/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_replica_replica_AndNodeCam */

#ifndef _Included_com_replica_replica_AndNodeCam
#define _Included_com_replica_replica_AndNodeCam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_replica_replica_AndNodeCam
 * Method:    sendData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_replica_replica_AndNodeCam_sendData
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_replica_replica_AndNodeCam
 * Method:    Initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_replica_replica_AndNodeCam_Initialize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
